//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeWizards.Client.CodeWizardServerProxy {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CodeWizardServerProxy.ICodeWizardsServer")]
    public interface ICodeWizardsServer {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICodeWizardsServer/WriteScroll", ReplyAction="http://tempuri.org/ICodeWizardsServer/WriteScrollResponse")]
        void WriteScroll(string token, string name, string code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICodeWizardsServer/Join", ReplyAction="http://tempuri.org/ICodeWizardsServer/JoinResponse")]
        string Join(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICodeWizardsServer/Leave", ReplyAction="http://tempuri.org/ICodeWizardsServer/LeaveResponse")]
        void Leave(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICodeWizardsServer/GetUpdate", ReplyAction="http://tempuri.org/ICodeWizardsServer/GetUpdateResponse")]
        CodeWizards.Contracts.WorldUpdate GetUpdate(string token);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICodeWizardsServerChannel : CodeWizards.Client.CodeWizardServerProxy.ICodeWizardsServer, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CodeWizardsServerClient : System.ServiceModel.ClientBase<CodeWizards.Client.CodeWizardServerProxy.ICodeWizardsServer>, CodeWizards.Client.CodeWizardServerProxy.ICodeWizardsServer {
        
        public CodeWizardsServerClient() {
        }
        
        public CodeWizardsServerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CodeWizardsServerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CodeWizardsServerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CodeWizardsServerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void WriteScroll(string token, string name, string code) {
            base.Channel.WriteScroll(token, name, code);
        }
        
        public string Join(string username) {
            return base.Channel.Join(username);
        }
        
        public void Leave(string token) {
            base.Channel.Leave(token);
        }
        
        public CodeWizards.Contracts.WorldUpdate GetUpdate(string token) {
            return base.Channel.GetUpdate(token);
        }
    }
}
